### ISSUE TITLE
ListCameras Error

### ISSUE THREAD

**Issue by Woselko** [sebastianguzmanmorla/LibCamera#1]
while listing camera in code I get an errors:

1.
Exception has occurred: CLR/System.FormatException
An exception of type 'System.FormatException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'The input string '1944 10-bit GBRG' was not in a correct format.'

2.
Exception has occurred: CLR/System.FormatException
An exception of type 'System.FormatException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'The input string '2464 10-bit RGGB' was not in a correct format.'

Probably one of the regex is wrong
I have 2 cameras connected
when I list cameras manually I got :

$ libcamera-hello --list-cameras
Available cameras
-----------------
**0 : ov5647 [2592x1944 10-bit GBRG] (/base/axi/pcie@120000/rp1/i2c@88000/ov5647@36)**
    Modes: 'SGBRG10_CSI2P' : 640x480 [58.92 fps - (16, 0)/2560x1920 crop]
                             1296x972 [43.25 fps - (0, 0)/2592x1944 crop]
                             1920x1080 [30.62 fps - (348, 434)/1928x1080 crop]
                             2592x1944 [15.63 fps - (0, 0)/2592x1944 crop]

1 : imx219 [3280x2464 10-bit RGGB] (/base/axi/pcie@120000/rp1/i2c@80000/imx219@10)
    Modes: 'SRGGB10_CSI2P' : 640x480 [206.65 fps - (1000, 752)/1280x960 crop]
                             1640x1232 [41.85 fps - (0, 0)/3280x2464 crop]
                             1920x1080 [47.57 fps - (680, 692)/1920x1080 crop]
                             3280x2464 [21.19 fps - (0, 0)/3280x2464 crop]
           'SRGGB8' : 640x480 [206.65 fps - (1000, 752)/1280x960 crop]
                      1640x1232 [83.70 fps - (0, 0)/3280x2464 crop]
                      1920x1080 [47.57 fps - (680, 692)/1920x1080 crop]
                      3280x2464 [21.19 fps - (0, 0)/3280x2464 crop]

**Comment by sebastianguzmanmorla** [comment]
Fixed and published in [https://www.nuget.org/packages/SebastianGuzmanMorla.LibCamera/1.0.2](url)

**Comment by Woselko** [comment]
thanks @sebastianguzmanmorla  I will check it. Well, im new to raspberry and all of IOT stuff. Do you handle capturing photos and videos with this nuget?

**Comment by sebastianguzmanmorla** [comment]
@Woselko i just added support to libcamera-still, please checkout [Example](https://github.com/sebastianguzmanmorla/LibCamera/blob/main/Example/Program.cs)  and [Nuget](https://www.nuget.org/packages/SebastianGuzmanMorla.LibCamera/1.0.3)
