### ISSUE TITLE
How to get the camera `Stream`?

### ISSUE THREAD

**Issue by paule96** [sebastianguzmanmorla/LibCamera#2]
hi @sebastianguzmanmorla,

how I can get the camera stream instead of the file?
Currently, this looks like it can only record to a file and then do the processing later with the recorded file.

**Comment by sebastianguzmanmorla** [comment]
Hi thanks for asking, here is a example what you need to do:

Set "Output" parameter of VideoSettings to "/dev/stdout" 

```c#
VideoSettings videoSettings = new H264()
{
    Camera = Camera.Id,
    Width = 1280,
    Height = 720,
    Timeout = 0,
    HFlip = true,
    VFlip = true,
    WhiteBalance = WhiteBalance.Incandescent,
    Mode = Camera.Modes.FirstOrDefault(),
    Output = "/dev/stdout" //This line is important to pipe the output
};
```

And finally make a task to read the output:

```c#
Task.Run(async () =>
{
    byte[]? Buffer = new byte[1024];
    int BytesRead = 0;

    while (!CaptureProcess.HasExited)
    {
        BytesRead = await CaptureProcess.StandardOutput.BaseStream.ReadAsync(Buffer);

        if (BytesRead > 0)
        {
            // Do something with the buffer bytes
        }
    }
});
```

If you have any more questions or doesn't work for you, feel free to keep questioning in this issue.
Good luck 👍

**Comment by Woselko** [comment]
> hi @sebastianguzmanmorla,
> 
> how I can get the camera stream instead of the file? Currently, this looks like it can only record to a file and then do the processing later with the recorded file.

Thats a good question

@sebastianguzmanmorla I will check it too! nice work!
